title          : "Predictive Analysis Workshop"
description    : >
  Explore data and .
long_description: |
  In this R project we will explore the workshop data file. This project assumes you can manipulate data frames using `dplyr` and make simple plots using `ggplot2`. You can learn these skills in the DataCamp courses.
language       : r
from           : 'r-notebooks-prod:41'
runtime_config : heavy
state          : live
technology: 1
instructors:
  - e2vinodj@yahoo.com
collaborators: []
prerequisites:
  - 4914
difficulty_level: 2
topics:
  - 3
  - 4
  - 12
time_needed: "60 minutes"

